blank_issues_enabled: true
contact_links:
  - name: Questions and support
    url: https://github.com/nexterias/actions-vercel/discussions/categories/q-a
    about: Ask questions and get help with actions-vercel.
