name: CI

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - dist/*
  push:
    branches: [main]
    paths-ignore:
      - dist/*
    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: "pnpm"
          node-version: 24

      - run: pnpm i --frozen-lock

      - run: pnpm lint

      - run: pnpm fmt:check

      - run: pnpm build

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: actions-vercel-dist
          path: ./dist

      - name: Commit dist files
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./dist
          git commit -m "build: update \`dist\` files" || true
          git push

  deploy:
    needs: [build]
    name: Deploy
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      deployments: write
      statuses: write
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: "pnpm"
          node-version: 24

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: actions-vercel-dist
          path: ./dist

      - uses: ./
        id: vercel
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          prebuilt: true
          production: ${{ github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest' }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}

      - run: |
          echo ${{ steps.vercel.outputs.deployment-url }}
          echo ${{ steps.vercel.outputs.deployment-status }}

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/') && github.actor != 'github-actions'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: "pnpm"
          node-version: 24

      - name: Setup git-cliff
        uses: kenji-miyake/setup-git-cliff@2778609c643a39a2576c4bae2e493b855eb4aee8 # v2

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        id: git-cliff
        with:
          result-encoding: string
          script: |
            const { stdout } = await exec.getExecOutput('git', ['cliff', '-l', '--strip', 'header'])
            return stdout

      - name: Create draft release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          draft: true
          body: ${{ steps.git-cliff.outputs.result }}

  tag:
    needs: [build]
    name: Tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.actor != 'github-actions'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Get target tag
        id: tag
        run: echo "name=$(echo '${{ github.ref }}' | sed -r 's/refs\/tags\/(v[0-9]+)\..*/\1/')" >> $GITHUB_OUTPUT

      - name: Update & Push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -f ${{ steps.tag.outputs.name }} ${{ github.ref }}
          git push -f --tags origin ${{ steps.tag.outputs.name }}
