name: Cleanup

on:
  delete:

jobs:
  cleanup:
    if: ${{ github.event.ref_type == 'branch' }}
    name: Clean up deployments
    runs-on: ubuntu-latest

    steps:
      - uses: nexterias/actions-vercel@94817372addf2649ad2276773237091f72470ae2 # main
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          org-id: ${{ secrets.VERCEL_ORG_ID }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          cleanup-deployment: true
